name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build imagen
        run: docker build --no-cache -t ${{ secrets.DOCKER_USER }}/pi-app ./SistemaGestion_2

      - name: Push imagen
        run: docker push ${{ secrets.DOCKER_USER }}/pi-app
